spring.application.name=api

api.app-url = https://tasktrackerapp.up.railway.app
server.port=${PORT:8081}

#postgresql://tododb_g08v_user:pdjx2g2qsdrgAtRXbEfTgTJk0UNGPNv2@dpg-d9bjr9urnols73et90qg-a/tododb_g08v
#postgresql://tododb_g08v_user:pdjx2g2qsdrgAtRXbEfTgTJk0UNGPNv2@dpg-d9bjr9urnols73et90qg-a.oregon-postgres.render.com/tododb_g08v
spring.datasource.url = jdbc:postgresql://thomas.proxy.rlwy.net:55300/task_tracker
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username = postgres
spring.datasource.password = ErdgnCSpYRoDuolmgtTClWnLFvtDNshX

server.error.whitelabel.enabled=false
#used to support form method navigation
spring.mvc.hiddenmethod.filter.enabled=true