#spring.application.name=api
#
#
##H2 in memory database
#spring.datasource.url = jdbc:h2:mem:tasktrackerdb
#spring.datasource.driver-class-name = org.h2.Driver
#spring.datasource.username = sa
#spring.datasource.password =
#
##JPA/Hibernate
#spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql = true
#
##Enable H2 console
#spring.h2.console.enabled = true
#spring.h2.console.path = /path-console

server.port=8081

#used to support form method navigation
spring.mvc.hiddenmethod.filter.enabled=true
