spring.application.name=api

api.app-url = https://tasktracker-r4x2.onrender.com
server.port=8081

#postgresql://tododb_g08v_user:pdjx2g2qsdrgAtRXbEfTgTJk0UNGPNv2@dpg-d9bjr9urnols73et90qg-a/tododb_g08v
#postgresql://tododb_g08v_user:pdjx2g2qsdrgAtRXbEfTgTJk0UNGPNv2@dpg-d9bjr9urnols73et90qg-a.oregon-postgres.render.com/tododb_g08v
spring.datasource.url = jdbc:postgresql://dpg-d9bjr9urnols73et90qg-a.oregon-postgres.render.com/tododb_g08v
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username = tododb_g08v_user
spring.datasource.password = pdjx2g2qsdrgAtRXbEfTgTJk0UNGPNv2

server.error.whitelabel.enabled=false
#used to support form method navigation
spring.mvc.hiddenmethod.filter.enabled=true